services:
    app:
        image: laravel-reverb-chat
        container_name: laravel-reverb-chat-app
        build: .
        volumes:
            - .:/app
        ports:
            - "8000:8000"
            - "2022:2022"
        environment:
            APP_ENV: local
            CONTAINER_ROLE: app

    queue:
        image: laravel-reverb-chat
        container_name: laravel-reverb-chat-queue
        depends_on:
            - app
        volumes:
            - .:/app
        ports:
            - "8080:8080"
        environment:
            APP_ENV: local
            CONTAINER_ROLE: queue

    reverb:
        image: laravel-reverb-chat
        container_name: laravel-reverb-chat-reverb
        depends_on:
            - app
        volumes:
            - .:/app
        environment:
            APP_ENV: local
            CONTAINER_ROLE: reverb
